#!/usr/bin/env bash
# End to end smoke test of CIG-SFT that runs on a CPU node in a couple of minutes.
#
# It exercises the whole path on the demo datasets that ship with the repository: the erased view is materialized, the
# credit is read from the frozen reference model and cached, the loss backpropagates and the step is logged. Nothing
# has to be downloaded apart from the tiny model.
#
# Usage:
#   bash example/scripts/smoke_train.sh
#   SMOKE_MODEL=/data/models/Qwen2.5-0.5B-Instruct bash example/scripts/smoke_train.sh
#   SMOKE_STEPS=5 bash example/scripts/smoke_train.sh
#
# Run it twice: the second run reports the credit as cached and reproduces the first loss, which is the check that the
# cache is lossless.

set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

SMOKE_MODEL="${SMOKE_MODEL:-Qwen/Qwen2.5-0.5B-Instruct}"
SMOKE_STEPS="${SMOKE_STEPS:-2}"
SMOKE_SAMPLES="${SMOKE_SAMPLES:-16}"
SMOKE_DIR="$ROOT/saves/smoke"
CONFIG="$SMOKE_DIR/cig_sft_smoke.yaml"

check_python_env
mkdir -p "$SMOKE_DIR"

cat > "$CONFIG" <<EOF
### Generated by example/scripts/smoke_train.sh, delete it freely.
model_path: $SMOKE_MODEL
trust_remote_code: true

stage: sft
do_train: true
finetuning_type: full
use_cig_sft_loss: true
cig_lambda: 0.3
cig_erased_prompt: default

dataset_dir: example/data
dataset: cig_sft_numina_cot_10k
template: qwen
cutoff_len: 512
max_samples: $SMOKE_SAMPLES
overwrite_cache: true
preprocessing_num_workers: 2
dataloader_num_workers: 0

output_dir: $SMOKE_DIR/run
cig_credit_cache: $SMOKE_DIR/credit.pt
logging_steps: 1
save_strategy: "no"
plot_loss: false
overwrite_output_dir: true
report_to: none

per_device_train_batch_size: 1
gradient_accumulation_steps: 2
max_steps: $SMOKE_STEPS
learning_rate: 1.0e-5
lr_scheduler_type: cosine
warmup_steps: 0
bf16: false
fp16: false
disable_tqdm: false
EOF

log "smoke config: $CONFIG (model $SMOKE_MODEL, $SMOKE_STEPS steps, $SMOKE_SAMPLES samples per dataset)"
log "the first run reads the credit of every example, the second one restores it from $SMOKE_DIR/credit.pt"

run_train "$CONFIG" "$@"

log "done. The log above must hold one of:"
log "  Read the CIG-SFT credit of N new and 0 cached examples.   (first run)"
log "  Read the CIG-SFT credit of 0 new and N cached examples.   (rerun, same loss)"
